#!/usr/bin/env python3
"""Follow SKKU-seeded researchers across later PubMed publications.

High-confidence mode follows authors by ORCID using PubMed Author Identifier [auid].
Optional name fallback is available for authors without ORCID, but it is lower confidence.

Input:
  papers.json generated by src/skku_pubmed_lineage.py

Outputs:
  author_registry.csv
  lineage_papers.csv / lineage_papers.json
  continuation_edges.csv / continuation_edges.json
  lineage_edges.csv / lineage_edges.json
  paper_annotations.csv / paper_annotations.json
  researcher_summary.csv / researcher_summary.json
  research_trajectory.html
  continuation.md
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import sys
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path

from skku_pubmed_lineage import Author, Paper, PubMedClient, is_skku_author
from skku_pubmed_annotation import PaperAnnotation, annotate_paper, progression_summary


@dataclass
class TrackedAuthor:
    key: str
    name: str
    orcid: str
    confidence: str
    seed_pmids: list[str]


@dataclass
class FollowedPaper:
    pmid: str
    year: int
    title: str
    journal: str
    doi: str
    pubmed_url: str
    tracked_authors: list[str]
    tracked_author_keys: list[str]
    current_affiliations: list[str]
    skku_current: bool
    primary_domain: str
    research_domains: list[str]
    topic_terms: list[str]
    disease_terms: list[str]
    methods: list[str]
    data_types: list[str]
    research_stage: str
    research_question: str


@dataclass
class ContinuationEdge:
    source: str
    target: str
    relation: str
    tracked_author: str
    author_key: str
    confidence: str
    evidence: str


@dataclass
class ResearchLineageEdge:
    source: str
    target: str
    relation: str
    score: float
    tracked_authors: list[str]
    confidence: str
    evidence: str
    source_stage: str = ""
    target_stage: str = ""
    progression: str = ""


@dataclass
class ResearcherTrajectory:
    key: str
    name: str
    orcid: str
    confidence: str
    paper_count: int
    first_year: int
    last_year: int
    top_domains: list[str]
    top_topics: list[str]
    top_diseases: list[str]
    top_methods: list[str]
    top_data_types: list[str]
    stage_path: list[str]
    strong_lineage_count: int
    trajectory_summary: str


def norm_name(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", " ", value.lower()).strip()


def load_seed(path: Path) -> list[dict]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise ValueError("Seed JSON must be a list generated by skku_pubmed_lineage.py")
    return data


def build_registry(seed_records: list[dict], allow_name_fallback: bool) -> list[TrackedAuthor]:
    by_orcid: dict[str, dict] = {}
    by_name: dict[str, dict] = {}

    for paper in seed_records:
        pmid = str(paper.get("pmid", ""))
        for author in paper.get("authors", []):
            name = author.get("name", "").strip()
            initials = author.get("initials", "").strip()
            affiliations = list(author.get("affiliations", []) or [])
            # Re-evaluate legacy seed records from raw affiliations so deep ORCID
            # selection uses the same conservative institution policy as STEP 2.
            if not is_skku_author(name, initials, affiliations):
                continue
            orcid = author.get("orcid", "").replace("https://orcid.org/", "").strip()

            if orcid:
                slot = by_orcid.setdefault(
                    orcid,
                    {"name": name, "seed_pmids": set()},
                )
                slot["seed_pmids"].add(pmid)
            elif allow_name_fallback and name:
                key = norm_name(name)
                slot = by_name.setdefault(
                    key,
                    {"name": name, "seed_pmids": set()},
                )
                slot["seed_pmids"].add(pmid)

    registry = []
    for orcid, info in by_orcid.items():
        registry.append(
            TrackedAuthor(
                key=f"orcid:{orcid}",
                name=info["name"],
                orcid=orcid,
                confidence="high",
                seed_pmids=sorted(info["seed_pmids"]),
            )
        )

    for key, info in by_name.items():
        registry.append(
            TrackedAuthor(
                key=f"name:{key}",
                name=info["name"],
                orcid="",
                confidence="low",
                seed_pmids=sorted(info["seed_pmids"]),
            )
        )

    return sorted(
        registry,
        key=lambda x: (
            x.confidence != "high",
            -len(x.seed_pmids),
            x.name.lower(),
        ),
    )


def author_query(author: TrackedAuthor, start_year: int, end_year: int) -> str:
    if author.orcid:
        base = f'"orcid {author.orcid}"[auid]'
    else:
        escaped = author.name.replace('"', "")
        base = f'"{escaped}"[fau]'

    if start_year and end_year:
        return f"{base} AND {start_year}:{end_year}[dp]"
    if start_year:
        return f"{base} AND {start_year}:3000[dp]"
    if end_year:
        return f"{base} AND 1800:{end_year}[dp]"
    return base


def matching_author(paper: Paper, tracked: TrackedAuthor) -> Author | None:
    if tracked.orcid:
        for author in paper.authors:
            if author.orcid and author.orcid == tracked.orcid:
                return author
        return None

    expected = norm_name(tracked.name)
    for author in paper.authors:
        if norm_name(author.name) == expected:
            return author
    return None


def collect_followups(
    client: PubMedClient,
    registry: list[TrackedAuthor],
    start_year: int,
    end_year: int,
    max_per_author: int,
) -> tuple[dict[str, Paper], dict[str, set[str]], dict[str, TrackedAuthor]]:
    papers: dict[str, Paper] = {}
    paper_authors: dict[str, set[str]] = defaultdict(set)
    registry_map = {x.key: x for x in registry}

    for idx, tracked in enumerate(registry, 1):
        query = author_query(tracked, start_year, end_year)
        count, ids = client.search(query, max_per_author)
        fetched = client.fetch(ids)
        matched = 0

        for paper in fetched:
            author = matching_author(paper, tracked)
            if author is None:
                continue
            papers[paper.pmid] = paper
            paper_authors[paper.pmid].add(tracked.key)
            matched += 1

        print(
            f"[author {idx}/{len(registry)}] {tracked.name} "
            f"confidence={tracked.confidence} PubMed={count} matched={matched}",
            file=sys.stderr,
        )

    return papers, paper_authors, registry_map


def make_followed_paper(
    paper: Paper,
    keys: set[str],
    registry_map: dict[str, TrackedAuthor],
    annotation: PaperAnnotation,
) -> FollowedPaper:
    tracked_names = []
    affiliations = []
    skku_current = False

    for key in sorted(keys):
        tracked = registry_map[key]
        tracked_names.append(tracked.name)
        matched = matching_author(paper, tracked)
        if matched:
            affiliations.extend(matched.affiliations)
            skku_current = skku_current or matched.is_skku

    return FollowedPaper(
        pmid=paper.pmid,
        year=paper.year,
        title=paper.title,
        journal=paper.journal,
        doi=paper.doi,
        pubmed_url=paper.pubmed_url,
        tracked_authors=tracked_names,
        tracked_author_keys=sorted(keys),
        current_affiliations=sorted(set(affiliations)),
        skku_current=skku_current,
        primary_domain=annotation.primary_domain,
        research_domains=annotation.research_domains,
        topic_terms=annotation.topic_terms,
        disease_terms=annotation.disease_terms,
        methods=annotation.methods,
        data_types=annotation.data_types,
        research_stage=annotation.research_stage,
        research_question=annotation.research_question,
    )


def make_continuation_edges(
    papers: dict[str, Paper],
    paper_authors: dict[str, set[str]],
    registry_map: dict[str, TrackedAuthor],
) -> list[ContinuationEdge]:
    by_author: dict[str, list[Paper]] = defaultdict(list)
    for pmid, keys in paper_authors.items():
        for key in keys:
            by_author[key].append(papers[pmid])

    edges = []
    seen = set()
    for key, author_papers in by_author.items():
        tracked = registry_map[key]
        ordered = sorted(
            author_papers,
            key=lambda p: (p.year or 9999, int(p.pmid) if p.pmid.isdigit() else 0),
        )
        for older, newer in zip(ordered, ordered[1:]):
            if older.pmid == newer.pmid:
                continue
            edge_key = (older.pmid, newer.pmid, key)
            if edge_key in seen:
                continue
            seen.add(edge_key)
            evidence = (
                f"ORCID {tracked.orcid}"
                if tracked.orcid
                else f"exact full-name match: {tracked.name}"
            )
            edges.append(
                ContinuationEdge(
                    source=older.pmid,
                    target=newer.pmid,
                    relation="author_continuation",
                    tracked_author=tracked.name,
                    author_key=key,
                    confidence=tracked.confidence,
                    evidence=evidence,
                )
            )
    return edges


def select_citation_check_pmids(
    papers: dict[str, Paper],
    paper_authors: dict[str, set[str]],
    max_citation_checks: int,
) -> list[str]:
    """Select citation checks fairly across tracked researchers.

    The previous PMID-sorted cap favored older records. This round-robin sampler
    distributes checks across researchers and prefers recent papers within each
    trajectory, then fills any remaining quota by recency.
    """
    if not papers:
        return []

    def sort_key(pmid: str):
        paper = papers[pmid]
        return (-(paper.year or 0), -(int(pmid) if pmid.isdigit() else 0))

    all_ids = sorted(papers, key=sort_key)
    if max_citation_checks <= 0 or max_citation_checks >= len(all_ids):
        return all_ids

    by_author: dict[str, list[str]] = defaultdict(list)
    for pmid, keys in paper_authors.items():
        if pmid not in papers:
            continue
        for key in keys:
            by_author[key].append(pmid)
    for key in by_author:
        by_author[key] = sorted(set(by_author[key]), key=sort_key)

    selected: list[str] = []
    seen: set[str] = set()
    index = 0
    author_keys = sorted(by_author)
    while len(selected) < max_citation_checks and author_keys:
        added = False
        for key in author_keys:
            items = by_author[key]
            if index >= len(items):
                continue
            pmid = items[index]
            if pmid not in seen:
                seen.add(pmid)
                selected.append(pmid)
                added = True
                if len(selected) >= max_citation_checks:
                    break
        if not added and all(index >= len(by_author[key]) for key in author_keys):
            break
        index += 1

    if len(selected) < max_citation_checks:
        for pmid in all_ids:
            if pmid in seen:
                continue
            selected.append(pmid)
            seen.add(pmid)
            if len(selected) >= max_citation_checks:
                break

    return selected


def add_direct_citation_edges(
    client: PubMedClient,
    papers: dict[str, Paper],
    paper_authors: dict[str, set[str]],
    edges: list[ContinuationEdge],
    max_citation_checks: int,
    stats: dict | None = None,
) -> list[ContinuationEdge]:
    ids = set(papers)
    seen = {(e.source, e.target, e.author_key) for e in edges}
    selected_ids = select_citation_check_pmids(
        papers,
        paper_authors,
        max_citation_checks,
    )

    for checked, pmid in enumerate(selected_ids, 1):
        refs = client.links(pmid, "pubmed_pubmed_refs")
        for ref in refs & ids:
            key = (ref, pmid, "citation")
            if key in seen:
                continue
            seen.add(key)
            edges.append(
                ContinuationEdge(
                    source=ref,
                    target=pmid,
                    relation="citation",
                    tracked_author="",
                    author_key="citation",
                    confidence="high",
                    evidence=f"{pmid} cites {ref}",
                )
            )
        if checked % 25 == 0:
            print(
                f"[citation] balanced checks {checked}/{len(selected_ids)}",
                file=sys.stderr,
            )

    if stats is not None:
        stats.update(
            {
                "citation_check_strategy": "balanced_by_researcher_recent_first",
                "citation_checks": len(selected_ids),
                "citation_checkable_papers": len(ids),
                "citation_coverage_fraction": round(
                    len(selected_ids) / len(ids), 6
                ) if ids else 0.0,
            }
        )
    return edges


def build_research_lineage_edges(
    edges: list[ContinuationEdge],
    paper_authors: dict[str, set[str]],
    registry_map: dict[str, TrackedAuthor],
    annotations: dict[str, PaperAnnotation] | None = None,
) -> list[ResearchLineageEdge]:
    """Collapse raw author/citation edges into interpretable research-lineage edges.

    Priority:
    1) same tracked researcher + direct citation + chronological continuation
    2) same tracked researcher + direct citation (non-consecutive publication)
    3) citation between different tracked researchers
    4) same tracked researcher only, without direct citation evidence
    """
    annotations = annotations or {}
    citation_pairs = {
        (e.source, e.target)
        for e in edges
        if e.relation == "citation"
    }
    output: dict[tuple[str, str, str, str], ResearchLineageEdge] = {}

    # Chronological publication-to-publication continuation for each tracked author.
    for edge in edges:
        if edge.relation != "author_continuation":
            continue

        has_direct_citation = (edge.source, edge.target) in citation_pairs
        if has_direct_citation:
            relation = "direct_citation_continuation"
            score = 1.0
            evidence = f"{edge.evidence}; {edge.target} directly cites {edge.source}"
        else:
            relation = "author_continuation_only"
            score = 0.75 if edge.confidence == "high" else 0.45
            evidence = f"{edge.evidence}; no direct PubMed citation detected between consecutive papers"

        source_ann = annotations.get(edge.source)
        target_ann = annotations.get(edge.target)
        item = ResearchLineageEdge(
            source=edge.source,
            target=edge.target,
            relation=relation,
            score=score,
            tracked_authors=[edge.tracked_author] if edge.tracked_author else [],
            confidence=edge.confidence,
            evidence=evidence,
            source_stage=source_ann.research_stage if source_ann else "",
            target_stage=target_ann.research_stage if target_ann else "",
            progression=(
                progression_summary(source_ann, target_ann)
                if source_ann and target_ann
                else ""
            ),
        )
        output[(item.source, item.target, item.relation, edge.author_key)] = item

    # Citation links that connect non-consecutive papers or different researchers.
    continuation_pairs = {
        (e.source, e.target)
        for e in edges
        if e.relation == "author_continuation"
    }
    for edge in edges:
        if edge.relation != "citation":
            continue
        if (edge.source, edge.target) in continuation_pairs:
            continue

        shared_keys = (
            paper_authors.get(edge.source, set())
            & paper_authors.get(edge.target, set())
        )
        if shared_keys:
            names = sorted({registry_map[k].name for k in shared_keys if k in registry_map})
            confidence = (
                "high"
                if shared_keys
                and all(registry_map[k].confidence == "high" for k in shared_keys if k in registry_map)
                else "mixed"
            )
            relation = "direct_citation_same_author"
            score = 0.95
            evidence = (
                f"{edge.target} directly cites {edge.source}; "
                f"same tracked researcher(s): {', '.join(names)}"
            )
        else:
            source_names = sorted(
                {
                    registry_map[k].name
                    for k in paper_authors.get(edge.source, set())
                    if k in registry_map
                }
            )
            target_names = sorted(
                {
                    registry_map[k].name
                    for k in paper_authors.get(edge.target, set())
                    if k in registry_map
                }
            )
            names = sorted(set(source_names + target_names))
            confidence = "high"
            relation = "cross_researcher_citation"
            score = 0.85
            evidence = (
                f"{edge.target} directly cites {edge.source}; "
                f"tracked researchers: {', '.join(names) or 'none'}"
            )

        source_ann = annotations.get(edge.source)
        target_ann = annotations.get(edge.target)
        item = ResearchLineageEdge(
            source=edge.source,
            target=edge.target,
            relation=relation,
            score=score,
            tracked_authors=names,
            confidence=confidence,
            evidence=evidence,
            source_stage=source_ann.research_stage if source_ann else "",
            target_stage=target_ann.research_stage if target_ann else "",
            progression=(
                progression_summary(source_ann, target_ann)
                if source_ann and target_ann
                else ""
            ),
        )
        output[(item.source, item.target, item.relation, "|".join(names))] = item

    return sorted(
        output.values(),
        key=lambda e: (-e.score, e.source, e.target, e.relation),
    )



def build_researcher_trajectories(
    registry: list[TrackedAuthor],
    followed: list[FollowedPaper],
    lineage_edges: list[ResearchLineageEdge],
) -> list[ResearcherTrajectory]:
    by_key: dict[str, list[FollowedPaper]] = defaultdict(list)
    for paper in followed:
        for key in paper.tracked_author_keys:
            by_key[key].append(paper)

    trajectories: list[ResearcherTrajectory] = []
    for tracked in registry:
        papers = sorted(
            by_key.get(tracked.key, []),
            key=lambda p: (p.year or 9999, int(p.pmid) if p.pmid.isdigit() else 0),
        )
        if not papers:
            continue

        domain_counts = Counter(value for paper in papers for value in paper.research_domains)
        topic_counts = Counter(value for paper in papers for value in paper.topic_terms)
        disease_counts = Counter(value for paper in papers for value in paper.disease_terms)
        method_counts = Counter(value for paper in papers for value in paper.methods)
        data_counts = Counter(value for paper in papers for value in paper.data_types)

        stage_path: list[str] = []
        for paper in papers:
            if not stage_path or stage_path[-1] != paper.research_stage:
                stage_path.append(paper.research_stage)

        strong_count = sum(
            edge.relation in {"direct_citation_continuation", "direct_citation_same_author"}
            and tracked.name in edge.tracked_authors
            for edge in lineage_edges
        )

        years = [p.year for p in papers if p.year]
        first_year = min(years) if years else 0
        last_year = max(years) if years else 0
        top_domains = [x for x, _ in domain_counts.most_common(5)]
        top_topics = [x for x, _ in topic_counts.most_common(8)]
        top_diseases = [x for x, _ in disease_counts.most_common(5)]
        top_methods = [x for x, _ in method_counts.most_common(5)]
        top_data = [x for x, _ in data_counts.most_common(5)]

        summary_parts = []
        if first_year and last_year:
            summary_parts.append(f"{first_year}–{last_year}")
        if top_domains:
            summary_parts.append("domain: " + ", ".join(top_domains[:2]))
        if top_topics:
            summary_parts.append("topics: " + ", ".join(top_topics[:2]))
        if stage_path:
            summary_parts.append("stage: " + " → ".join(stage_path))
        if top_methods:
            summary_parts.append("methods: " + ", ".join(top_methods[:3]))
        if top_data:
            summary_parts.append("data: " + ", ".join(top_data[:3]))
        if top_diseases:
            summary_parts.append("disease: " + ", ".join(top_diseases[:2]))
        summary_parts.append(f"strong citation lineage: {strong_count}")

        trajectories.append(
            ResearcherTrajectory(
                key=tracked.key,
                name=tracked.name,
                orcid=tracked.orcid,
                confidence=tracked.confidence,
                paper_count=len(papers),
                first_year=first_year,
                last_year=last_year,
                top_domains=top_domains,
                top_topics=top_topics,
                top_diseases=top_diseases,
                top_methods=top_methods,
                top_data_types=top_data,
                stage_path=stage_path,
                strong_lineage_count=strong_count,
                trajectory_summary=" · ".join(summary_parts),
            )
        )

    return sorted(
        trajectories,
        key=lambda x: (-x.strong_lineage_count, -x.paper_count, x.name.lower()),
    )


def render_research_trajectory_html(
    path: Path,
    followed: list[FollowedPaper],
    lineage_edges: list[ResearchLineageEdge],
    trajectories: list[ResearcherTrajectory],
) -> None:
    paper_map = {p.pmid: p for p in followed}

    nodes = []
    for paper in followed:
        short_title = paper.title if len(paper.title) <= 70 else paper.title[:67] + "..."
        domain = paper.primary_domain or "not classified"
        topics = ", ".join(paper.topic_terms[:3]) or "not classified"
        disease = ", ".join(paper.disease_terms[:3]) or "not classified"
        methods = ", ".join(paper.methods[:3]) or "not classified"
        data_types = ", ".join(paper.data_types[:3]) or "not classified"
        tracked = ", ".join(paper.tracked_authors)
        tooltip = (
            f"<b>{paper.title}</b><br>"
            f"PMID: {paper.pmid}<br>"
            f"Year: {paper.year or 'Unknown'}<br>"
            f"Researchers: {tracked}<br>"
            f"Domain: {domain}<br>"
            f"Topics: {topics}<br>"
            f"Stage: {paper.research_stage}<br>"
            f"Disease: {disease}<br>"
            f"Methods: {methods}<br>"
            f"Data: {data_types}<br>"
            f"Question: {paper.research_question}"
        )
        nodes.append(
            {
                "id": paper.pmid,
                "label": f"{paper.year or '?'} | {paper.research_stage}\\n{short_title}",
                "title": tooltip,
                "group": paper.research_stage,
                "url": paper.pubmed_url,
                "authors": paper.tracked_authors,
            }
        )

    graph_edges = []
    for idx, edge in enumerate(lineage_edges):
        if edge.source not in paper_map or edge.target not in paper_map:
            continue
        width = 4 if edge.score >= 0.95 else (3 if edge.score >= 0.85 else 1.5)
        dashes = edge.score < 0.85
        title = (
            f"{edge.relation} | score={edge.score:.2f}"
            + (f"<br>{edge.progression}" if edge.progression else "")
            + f"<br>{edge.evidence}"
        )
        graph_edges.append(
            {
                "id": f"e{idx}",
                "from": edge.source,
                "to": edge.target,
                "arrows": "to",
                "width": width,
                "dashes": dashes,
                "title": title,
                "authors": edge.tracked_authors,
                "relation": edge.relation,
                "score": edge.score,
            }
        )

    researcher_options = [
        {"key": item.key, "name": item.name, "summary": item.trajectory_summary}
        for item in trajectories
    ]

    payload_nodes = json.dumps(nodes, ensure_ascii=False)
    payload_edges = json.dumps(graph_edges, ensure_ascii=False)
    payload_researchers = json.dumps(researcher_options, ensure_ascii=False)

    html = f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>SKKU PubMed Research Trajectory</title>
<script src="https://unpkg.com/vis-network/standalone/umd/vis-network.min.js"></script>
<style>
body {{ font-family: Arial, sans-serif; margin: 0; background: #fafafa; }}
header {{ padding: 16px 20px; background: white; border-bottom: 1px solid #ddd; }}
.controls {{ display: flex; gap: 12px; align-items: center; flex-wrap: wrap; }}
select {{ padding: 7px 10px; min-width: 260px; }}
#summary {{ margin-top: 8px; font-size: 13px; color: #444; }}
#network {{ height: 78vh; background: white; }}
.legend {{ padding: 10px 20px; font-size: 12px; background: white; border-top: 1px solid #ddd; }}
.badge {{ display: inline-block; margin-right: 14px; }}
</style>
</head>
<body>
<header>
  <h2 style="margin:0 0 10px 0">SKKU-seeded PubMed Research Trajectory</h2>
  <div class="controls">
    <label>Researcher:
      <select id="researcher"><option value="">All researchers</option></select>
    </label>
    <label><input type="checkbox" id="strongOnly"> strong citation lineage only (score ≥ 0.95)</label>
  </div>
  <div id="summary">All tracked researchers</div>
</header>
<div id="network"></div>
<div class="legend">
  <span class="badge"><b>Solid/thick</b>: stronger citation-supported lineage</span>
  <span class="badge"><b>Dashed/thin</b>: ORCID/name continuation without direct citation</span>
  <span class="badge">Double-click a paper to open PubMed</span>
</div>
<script>
const allNodes = {payload_nodes};
const allEdges = {payload_edges};
const researchers = {payload_researchers};

const select = document.getElementById("researcher");
for (const r of researchers) {{
  const opt = document.createElement("option");
  opt.value = r.name;
  opt.textContent = r.name;
  select.appendChild(opt);
}}
const summaryMap = Object.fromEntries(researchers.map(r => [r.name, r.summary]));

const network = new vis.Network(
  document.getElementById("network"),
  {{ nodes: new vis.DataSet([]), edges: new vis.DataSet([]) }},
  {{
    layout: {{ improvedLayout: true }},
    physics: {{ stabilization: true, barnesHut: {{ gravitationalConstant: -12000 }} }},
    interaction: {{ hover: true, navigationButtons: true }},
    nodes: {{ shape: "box", margin: 10, font: {{ multi: "html", size: 12 }} }},
    edges: {{ smooth: {{ type: "dynamic" }} }}
  }}
);

function redraw() {{
  const name = select.value;
  const strongOnly = document.getElementById("strongOnly").checked;

  let nodes = allNodes.filter(n => !name || n.authors.includes(name));
  const ids = new Set(nodes.map(n => n.id));
  let edges = allEdges.filter(e =>
    ids.has(e.from) && ids.has(e.to) &&
    (!name || e.authors.includes(name)) &&
    (!strongOnly || e.score >= 0.95)
  );

  if (strongOnly) {{
    const edgeIds = new Set();
    for (const e of edges) {{ edgeIds.add(e.from); edgeIds.add(e.to); }}
    nodes = nodes.filter(n => edgeIds.has(n.id));
  }}

  network.setData({{
    nodes: new vis.DataSet(nodes),
    edges: new vis.DataSet(edges)
  }});

  if (name) {{
    document.getElementById("summary").textContent = summaryMap[name] || name;
  }} else {{
    document.getElementById("summary").textContent =
      "All tracked researchers · papers=" + nodes.length + " · edges=" + edges.length;
  }}
  if (nodes.length) network.fit();
}}

select.addEventListener("change", redraw);
document.getElementById("strongOnly").addEventListener("change", redraw);
network.on("doubleClick", params => {{
  if (!params.nodes.length) return;
  const node = allNodes.find(n => n.id === params.nodes[0]);
  if (node && node.url) window.open(node.url, "_blank");
}});
redraw();
</script>
</body>
</html>
"""
    path.write_text(html, encoding="utf-8")


def write_csv(path: Path, rows: list[dict]) -> None:
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    with path.open("w", newline="", encoding="utf-8-sig") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def write_report(
    path: Path,
    registry: list[TrackedAuthor],
    followed: list[FollowedPaper],
    edges: list[ContinuationEdge],
    lineage_edges: list[ResearchLineageEdge],
) -> None:
    author_counts = Counter()
    by_key: dict[str, list[FollowedPaper]] = defaultdict(list)
    for paper in followed:
        for key, name in zip(paper.tracked_author_keys, paper.tracked_authors):
            author_counts[name] += 1
            by_key[key].append(paper)

    rel_counts = Counter(e.relation for e in edges)
    lineage_counts = Counter(e.relation for e in lineage_edges)
    lines = [
        "# SKKU-seeded PubMed Author Continuation",
        "",
        f"- Generated UTC: {datetime.now(timezone.utc).isoformat(timespec='seconds')}",
        f"- Tracked researchers: {len(registry)}",
        f"- Unique followed publications: {len(followed)}",
        f"- Author-continuation edges: {rel_counts['author_continuation']}",
        f"- Direct citation edges: {rel_counts['citation']}",
        f"- Strong direct-citation continuations: {lineage_counts['direct_citation_continuation']}",
        f"- Direct citations within same researcher: {lineage_counts['direct_citation_same_author']}",
        f"- Author-only continuations: {lineage_counts['author_continuation_only']}",
        "",
        "## Lineage interpretation",
        "",
        "- Score 1.00: same tracked researcher and the later consecutive paper directly cites the earlier paper.",
        "- Score 0.95: same tracked researcher with a direct citation, but the papers are not consecutive in the publication timeline.",
        "- Score 0.85: direct citation between papers belonging to different tracked researchers.",
        "- Score 0.75: exact ORCID researcher continuation without a direct citation between consecutive papers.",
        "- Score 0.45: name-only researcher continuation without direct citation evidence.",
        "",
        "## Identity policy",
        "",
        "- High confidence: exact ORCID match through PubMed Author Identifier.",
        "- Low confidence: exact full-author-name fallback; manual review is recommended.",
        "- SKKU status here is seeded from publication-time affiliation, not proof of graduation/alumni status.",
        "",
        "## Researchers",
        "",
        "| Researcher | Confidence | ORCID | Followed papers |",
        "|---|---|---|---:|",
    ]
    for tracked in registry:
        lines.append(
            f"| {tracked.name} | {tracked.confidence} | {tracked.orcid or '-'} | "
            f"{len(by_key.get(tracked.key, []))} |"
        )

    lines += ["", "## Publication chains", ""]
    for tracked in registry:
        chain = sorted(
            by_key.get(tracked.key, []),
            key=lambda p: (p.year or 9999, p.pmid),
        )
        if not chain:
            continue
        lines.append(f"### {tracked.name}")
        lines.append(
            f"Confidence: **{tracked.confidence}**"
            + (f" · ORCID: {tracked.orcid}" if tracked.orcid else "")
        )
        for paper in chain:
            aff = "SKKU" if paper.skku_current else "non-SKKU / other affiliation"
            methods = ", ".join(paper.methods[:3]) or "method not classified"
            data_types = ", ".join(paper.data_types[:3]) or "data not classified"
            domain = paper.primary_domain or "domain not classified"
            topics = ", ".join(paper.topic_terms[:2]) or "topic not classified"
            disease = ", ".join(paper.disease_terms[:2]) or "phenotype not classified"
            lines.append(
                f"- {paper.year or 'Unknown'} · PMID {paper.pmid} · "
                f"[{paper.title}]({paper.pubmed_url}) · {aff} · "
                f"domain={domain} · topics={topics} · stage={paper.research_stage} · "
                f"disease={disease} · method={methods} · data={data_types}"
            )
            lines.append(f"  - Question: {paper.research_question}")
        lines.append("")

    strong = [
        edge for edge in lineage_edges
        if edge.relation in {"direct_citation_continuation", "direct_citation_same_author"}
    ]
    if strong:
        lines += ["", "## Strong research progression", ""]
        for edge in strong[:50]:
            names = ", ".join(edge.tracked_authors) or "tracked researcher"
            lines.append(
                f"- PMID {edge.source} → {edge.target} · {names} · "
                f"score={edge.score:.2f} · {edge.progression or 'continuation'}"
            )

    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Follow SKKU-seeded authors across later PubMed publications."
    )
    parser.add_argument("--seed-json", default="outputs/skku_pubmed_lineage/papers.json")
    parser.add_argument("--email", default=os.getenv("NCBI_EMAIL", ""))
    parser.add_argument("--api-key", default=os.getenv("NCBI_API_KEY", ""))
    parser.add_argument("--start-year", type=int, default=2002)
    parser.add_argument("--end-year", type=int, default=datetime.now().year)
    parser.add_argument("--max-authors", type=int, default=100)
    parser.add_argument("--max-per-author", type=int, default=200)
    parser.add_argument("--allow-name-fallback", action="store_true")
    parser.add_argument("--with-citations", action="store_true")
    parser.add_argument("--max-citation-checks", type=int, default=300)
    parser.add_argument("--output-dir", default="outputs/skku_pubmed_followup")
    args = parser.parse_args()

    if not args.email:
        parser.error("Provide --email or set NCBI_EMAIL.")

    seed_records = load_seed(Path(args.seed_json))
    registry = build_registry(seed_records, args.allow_name_fallback)
    registry = registry[: args.max_authors]
    print(
        f"[registry] researchers={len(registry)} "
        f"(ORCID-first; ranked by SKKU seed-paper count; "
        f"name fallback={args.allow_name_fallback})",
        file=sys.stderr,
    )

    client = PubMedClient(args.email, args.api_key)
    papers, paper_authors, registry_map = collect_followups(
        client=client,
        registry=registry,
        start_year=args.start_year,
        end_year=args.end_year,
        max_per_author=args.max_per_author,
    )

    annotations = {
        pmid: annotate_paper(paper)
        for pmid, paper in papers.items()
    }

    followed = [
        make_followed_paper(papers[pmid], keys, registry_map, annotations[pmid])
        for pmid, keys in paper_authors.items()
    ]
    followed.sort(key=lambda p: (p.year, p.pmid), reverse=True)

    edges = make_continuation_edges(papers, paper_authors, registry_map)
    citation_stats: dict = {
        "citation_check_strategy": "disabled",
        "citation_checks": 0,
        "citation_checkable_papers": len(papers),
        "citation_coverage_fraction": 0.0,
    }
    if args.with_citations:
        edges = add_direct_citation_edges(
            client,
            papers,
            paper_authors,
            edges,
            args.max_citation_checks,
            stats=citation_stats,
        )

    lineage_edges = build_research_lineage_edges(
        edges,
        paper_authors,
        registry_map,
        annotations,
    )
    trajectories = build_researcher_trajectories(
        registry,
        followed,
        lineage_edges,
    )

    out = Path(args.output_dir)
    out.mkdir(parents=True, exist_ok=True)

    registry_rows = []
    for item in registry:
        row = asdict(item)
        row["seed_pmids"] = "; ".join(item.seed_pmids)
        registry_rows.append(row)
    write_csv(out / "author_registry.csv", registry_rows)

    followed_rows = []
    for item in followed:
        row = asdict(item)
        row["tracked_authors"] = "; ".join(item.tracked_authors)
        row["tracked_author_keys"] = "; ".join(item.tracked_author_keys)
        row["current_affiliations"] = " | ".join(item.current_affiliations)
        row["research_domains"] = "; ".join(item.research_domains)
        row["topic_terms"] = "; ".join(item.topic_terms)
        row["disease_terms"] = "; ".join(item.disease_terms)
        row["methods"] = "; ".join(item.methods)
        row["data_types"] = "; ".join(item.data_types)
        followed_rows.append(row)
    write_csv(out / "lineage_papers.csv", followed_rows)

    annotation_rows = []
    for item in annotations.values():
        row = asdict(item)
        row["research_domains"] = "; ".join(item.research_domains)
        row["topic_terms"] = "; ".join(item.topic_terms)
        row["disease_terms"] = "; ".join(item.disease_terms)
        row["methods"] = "; ".join(item.methods)
        row["data_types"] = "; ".join(item.data_types)
        row["evidence_terms"] = "; ".join(item.evidence_terms)
        annotation_rows.append(row)
    write_csv(out / "paper_annotations.csv", annotation_rows)

    trajectory_rows = []
    for item in trajectories:
        row = asdict(item)
        row["top_domains"] = "; ".join(item.top_domains)
        row["top_topics"] = "; ".join(item.top_topics)
        row["top_diseases"] = "; ".join(item.top_diseases)
        row["top_methods"] = "; ".join(item.top_methods)
        row["top_data_types"] = "; ".join(item.top_data_types)
        row["stage_path"] = " -> ".join(item.stage_path)
        trajectory_rows.append(row)
    write_csv(out / "researcher_summary.csv", trajectory_rows)

    write_csv(out / "continuation_edges.csv", [asdict(e) for e in edges])

    lineage_rows = []
    for item in lineage_edges:
        row = asdict(item)
        row["tracked_authors"] = "; ".join(item.tracked_authors)
        lineage_rows.append(row)
    write_csv(out / "lineage_edges.csv", lineage_rows)

    (out / "lineage_papers.json").write_text(
        json.dumps([asdict(x) for x in followed], ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    (out / "paper_annotations.json").write_text(
        json.dumps([asdict(x) for x in annotations.values()], ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    (out / "continuation_edges.json").write_text(
        json.dumps([asdict(x) for x in edges], ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    (out / "lineage_edges.json").write_text(
        json.dumps([asdict(x) for x in lineage_edges], ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    (out / "researcher_summary.json").write_text(
        json.dumps([asdict(x) for x in trajectories], ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    render_research_trajectory_html(
        out / "research_trajectory.html",
        followed,
        lineage_edges,
        trajectories,
    )
    write_report(out / "continuation.md", registry, followed, edges, lineage_edges)

    summary = {
        "followup_version": 4,
        "registry_policy": "conservative_affiliation_then_seed_paper_count_ranking",
        "start_year": args.start_year,
        "end_year": args.end_year,
        "max_authors": args.max_authors,
        "max_per_author": args.max_per_author,
        "max_citation_checks": args.max_citation_checks,
        **citation_stats,
        "tracked_researchers": len(registry),
        "high_confidence_orcid": sum(x.confidence == "high" for x in registry),
        "low_confidence_name": sum(x.confidence == "low" for x in registry),
        "unique_followed_papers": len(followed),
        "edges": len(edges),
        "edge_types": dict(Counter(e.relation for e in edges)),
        "lineage_edges": len(lineage_edges),
        "lineage_types": dict(Counter(e.relation for e in lineage_edges)),
        "strong_direct_lineage": sum(
            e.relation in {"direct_citation_continuation", "direct_citation_same_author"}
            for e in lineage_edges
        ),
        "annotated_papers": len(annotations),
        "papers_with_methods": sum(bool(a.methods) for a in annotations.values()),
        "papers_with_data_types": sum(bool(a.data_types) for a in annotations.values()),
        "papers_with_disease_terms": sum(bool(a.disease_terms) for a in annotations.values()),
        "primary_domain_counts": dict(Counter(a.primary_domain for a in annotations.values())),
        "research_stages": dict(Counter(a.research_stage for a in annotations.values())),
        "researcher_trajectories": len(trajectories),
        "researchers_with_strong_lineage": sum(
            t.strong_lineage_count > 0 for t in trajectories
        ),
    }
    (out / "summary.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
