#!/usr/bin/env python3
"""Follow SKKU-seeded researchers across later PubMed publications.

High-confidence mode follows authors by ORCID using PubMed Author Identifier [auid].
Optional name fallback is available for authors without ORCID, but it is lower confidence.

Input:
  papers.json generated by src/skku_pubmed_lineage.py

Outputs:
  author_registry.csv
  lineage_papers.csv / lineage_papers.json
  continuation_edges.csv / continuation_edges.json
  lineage_edges.csv / lineage_edges.json
  continuation.md
"""

from __future__ import annotations

import argparse
import csv
import json
import os
import re
import sys
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass
from datetime import datetime, timezone
from pathlib import Path

from skku_pubmed_lineage import Author, Paper, PubMedClient


@dataclass
class TrackedAuthor:
    key: str
    name: str
    orcid: str
    confidence: str
    seed_pmids: list[str]


@dataclass
class FollowedPaper:
    pmid: str
    year: int
    title: str
    journal: str
    doi: str
    pubmed_url: str
    tracked_authors: list[str]
    tracked_author_keys: list[str]
    current_affiliations: list[str]
    skku_current: bool


@dataclass
class ContinuationEdge:
    source: str
    target: str
    relation: str
    tracked_author: str
    author_key: str
    confidence: str
    evidence: str


@dataclass
class ResearchLineageEdge:
    source: str
    target: str
    relation: str
    score: float
    tracked_authors: list[str]
    confidence: str
    evidence: str


def norm_name(value: str) -> str:
    return re.sub(r"[^a-z0-9]+", " ", value.lower()).strip()


def load_seed(path: Path) -> list[dict]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, list):
        raise ValueError("Seed JSON must be a list generated by skku_pubmed_lineage.py")
    return data


def build_registry(seed_records: list[dict], allow_name_fallback: bool) -> list[TrackedAuthor]:
    by_orcid: dict[str, dict] = {}
    by_name: dict[str, dict] = {}

    for paper in seed_records:
        pmid = str(paper.get("pmid", ""))
        for author in paper.get("authors", []):
            if not author.get("is_skku"):
                continue
            name = author.get("name", "").strip()
            orcid = author.get("orcid", "").replace("https://orcid.org/", "").strip()

            if orcid:
                slot = by_orcid.setdefault(
                    orcid,
                    {"name": name, "seed_pmids": set()},
                )
                slot["seed_pmids"].add(pmid)
            elif allow_name_fallback and name:
                key = norm_name(name)
                slot = by_name.setdefault(
                    key,
                    {"name": name, "seed_pmids": set()},
                )
                slot["seed_pmids"].add(pmid)

    registry = []
    for orcid, info in by_orcid.items():
        registry.append(
            TrackedAuthor(
                key=f"orcid:{orcid}",
                name=info["name"],
                orcid=orcid,
                confidence="high",
                seed_pmids=sorted(info["seed_pmids"]),
            )
        )

    for key, info in by_name.items():
        registry.append(
            TrackedAuthor(
                key=f"name:{key}",
                name=info["name"],
                orcid="",
                confidence="low",
                seed_pmids=sorted(info["seed_pmids"]),
            )
        )

    return sorted(registry, key=lambda x: (x.confidence != "high", x.name.lower()))


def author_query(author: TrackedAuthor, start_year: int, end_year: int) -> str:
    if author.orcid:
        base = f'"orcid {author.orcid}"[auid]'
    else:
        escaped = author.name.replace('"', "")
        base = f'"{escaped}"[fau]'

    if start_year and end_year:
        return f"{base} AND {start_year}:{end_year}[dp]"
    if start_year:
        return f"{base} AND {start_year}:3000[dp]"
    if end_year:
        return f"{base} AND 1800:{end_year}[dp]"
    return base


def matching_author(paper: Paper, tracked: TrackedAuthor) -> Author | None:
    if tracked.orcid:
        for author in paper.authors:
            if author.orcid and author.orcid == tracked.orcid:
                return author
        return None

    expected = norm_name(tracked.name)
    for author in paper.authors:
        if norm_name(author.name) == expected:
            return author
    return None


def collect_followups(
    client: PubMedClient,
    registry: list[TrackedAuthor],
    start_year: int,
    end_year: int,
    max_per_author: int,
) -> tuple[dict[str, Paper], dict[str, set[str]], dict[str, TrackedAuthor]]:
    papers: dict[str, Paper] = {}
    paper_authors: dict[str, set[str]] = defaultdict(set)
    registry_map = {x.key: x for x in registry}

    for idx, tracked in enumerate(registry, 1):
        query = author_query(tracked, start_year, end_year)
        count, ids = client.search(query, max_per_author)
        fetched = client.fetch(ids)
        matched = 0

        for paper in fetched:
            author = matching_author(paper, tracked)
            if author is None:
                continue
            papers[paper.pmid] = paper
            paper_authors[paper.pmid].add(tracked.key)
            matched += 1

        print(
            f"[author {idx}/{len(registry)}] {tracked.name} "
            f"confidence={tracked.confidence} PubMed={count} matched={matched}",
            file=sys.stderr,
        )

    return papers, paper_authors, registry_map


def make_followed_paper(
    paper: Paper,
    keys: set[str],
    registry_map: dict[str, TrackedAuthor],
) -> FollowedPaper:
    tracked_names = []
    affiliations = []
    skku_current = False

    for key in sorted(keys):
        tracked = registry_map[key]
        tracked_names.append(tracked.name)
        matched = matching_author(paper, tracked)
        if matched:
            affiliations.extend(matched.affiliations)
            skku_current = skku_current or matched.is_skku

    return FollowedPaper(
        pmid=paper.pmid,
        year=paper.year,
        title=paper.title,
        journal=paper.journal,
        doi=paper.doi,
        pubmed_url=paper.pubmed_url,
        tracked_authors=tracked_names,
        tracked_author_keys=sorted(keys),
        current_affiliations=sorted(set(affiliations)),
        skku_current=skku_current,
    )


def make_continuation_edges(
    papers: dict[str, Paper],
    paper_authors: dict[str, set[str]],
    registry_map: dict[str, TrackedAuthor],
) -> list[ContinuationEdge]:
    by_author: dict[str, list[Paper]] = defaultdict(list)
    for pmid, keys in paper_authors.items():
        for key in keys:
            by_author[key].append(papers[pmid])

    edges = []
    seen = set()
    for key, author_papers in by_author.items():
        tracked = registry_map[key]
        ordered = sorted(
            author_papers,
            key=lambda p: (p.year or 9999, int(p.pmid) if p.pmid.isdigit() else 0),
        )
        for older, newer in zip(ordered, ordered[1:]):
            if older.pmid == newer.pmid:
                continue
            edge_key = (older.pmid, newer.pmid, key)
            if edge_key in seen:
                continue
            seen.add(edge_key)
            evidence = (
                f"ORCID {tracked.orcid}"
                if tracked.orcid
                else f"exact full-name match: {tracked.name}"
            )
            edges.append(
                ContinuationEdge(
                    source=older.pmid,
                    target=newer.pmid,
                    relation="author_continuation",
                    tracked_author=tracked.name,
                    author_key=key,
                    confidence=tracked.confidence,
                    evidence=evidence,
                )
            )
    return edges


def add_direct_citation_edges(
    client: PubMedClient,
    papers: dict[str, Paper],
    edges: list[ContinuationEdge],
    max_citation_checks: int,
) -> list[ContinuationEdge]:
    ids = set(papers)
    seen = {(e.source, e.target, e.author_key) for e in edges}
    checked = 0

    for pmid in sorted(ids):
        if max_citation_checks and checked >= max_citation_checks:
            break
        checked += 1
        refs = client.links(pmid, "pubmed_pubmed_refs")
        for ref in refs & ids:
            key = (ref, pmid, "citation")
            if key in seen:
                continue
            seen.add(key)
            edges.append(
                ContinuationEdge(
                    source=ref,
                    target=pmid,
                    relation="citation",
                    tracked_author="",
                    author_key="citation",
                    confidence="high",
                    evidence=f"{pmid} cites {ref}",
                )
            )
        if checked % 25 == 0:
            print(f"[citation] checked {checked}/{min(len(ids), max_citation_checks or len(ids))}", file=sys.stderr)

    return edges


def build_research_lineage_edges(
    edges: list[ContinuationEdge],
    paper_authors: dict[str, set[str]],
    registry_map: dict[str, TrackedAuthor],
) -> list[ResearchLineageEdge]:
    """Collapse raw author/citation edges into interpretable research-lineage edges.

    Priority:
    1) same tracked researcher + direct citation + chronological continuation
    2) same tracked researcher + direct citation (non-consecutive publication)
    3) citation between different tracked researchers
    4) same tracked researcher only, without direct citation evidence
    """
    citation_pairs = {
        (e.source, e.target)
        for e in edges
        if e.relation == "citation"
    }
    output: dict[tuple[str, str, str, str], ResearchLineageEdge] = {}

    # Chronological publication-to-publication continuation for each tracked author.
    for edge in edges:
        if edge.relation != "author_continuation":
            continue

        has_direct_citation = (edge.source, edge.target) in citation_pairs
        if has_direct_citation:
            relation = "direct_citation_continuation"
            score = 1.0
            evidence = f"{edge.evidence}; {edge.target} directly cites {edge.source}"
        else:
            relation = "author_continuation_only"
            score = 0.75 if edge.confidence == "high" else 0.45
            evidence = f"{edge.evidence}; no direct PubMed citation detected between consecutive papers"

        item = ResearchLineageEdge(
            source=edge.source,
            target=edge.target,
            relation=relation,
            score=score,
            tracked_authors=[edge.tracked_author] if edge.tracked_author else [],
            confidence=edge.confidence,
            evidence=evidence,
        )
        output[(item.source, item.target, item.relation, edge.author_key)] = item

    # Citation links that connect non-consecutive papers or different researchers.
    continuation_pairs = {
        (e.source, e.target)
        for e in edges
        if e.relation == "author_continuation"
    }
    for edge in edges:
        if edge.relation != "citation":
            continue
        if (edge.source, edge.target) in continuation_pairs:
            continue

        shared_keys = (
            paper_authors.get(edge.source, set())
            & paper_authors.get(edge.target, set())
        )
        if shared_keys:
            names = sorted({registry_map[k].name for k in shared_keys if k in registry_map})
            confidence = (
                "high"
                if shared_keys
                and all(registry_map[k].confidence == "high" for k in shared_keys if k in registry_map)
                else "mixed"
            )
            relation = "direct_citation_same_author"
            score = 0.95
            evidence = (
                f"{edge.target} directly cites {edge.source}; "
                f"same tracked researcher(s): {', '.join(names)}"
            )
        else:
            source_names = sorted(
                {
                    registry_map[k].name
                    for k in paper_authors.get(edge.source, set())
                    if k in registry_map
                }
            )
            target_names = sorted(
                {
                    registry_map[k].name
                    for k in paper_authors.get(edge.target, set())
                    if k in registry_map
                }
            )
            names = sorted(set(source_names + target_names))
            confidence = "high"
            relation = "cross_researcher_citation"
            score = 0.85
            evidence = (
                f"{edge.target} directly cites {edge.source}; "
                f"tracked researchers: {', '.join(names) or 'none'}"
            )

        item = ResearchLineageEdge(
            source=edge.source,
            target=edge.target,
            relation=relation,
            score=score,
            tracked_authors=names,
            confidence=confidence,
            evidence=evidence,
        )
        output[(item.source, item.target, item.relation, "|".join(names))] = item

    return sorted(
        output.values(),
        key=lambda e: (-e.score, e.source, e.target, e.relation),
    )


def write_csv(path: Path, rows: list[dict]) -> None:
    if not rows:
        path.write_text("", encoding="utf-8")
        return
    with path.open("w", newline="", encoding="utf-8-sig") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def write_report(
    path: Path,
    registry: list[TrackedAuthor],
    followed: list[FollowedPaper],
    edges: list[ContinuationEdge],
    lineage_edges: list[ResearchLineageEdge],
) -> None:
    author_counts = Counter()
    by_key: dict[str, list[FollowedPaper]] = defaultdict(list)
    for paper in followed:
        for key, name in zip(paper.tracked_author_keys, paper.tracked_authors):
            author_counts[name] += 1
            by_key[key].append(paper)

    rel_counts = Counter(e.relation for e in edges)
    lineage_counts = Counter(e.relation for e in lineage_edges)
    lines = [
        "# SKKU-seeded PubMed Author Continuation",
        "",
        f"- Generated UTC: {datetime.now(timezone.utc).isoformat(timespec='seconds')}",
        f"- Tracked researchers: {len(registry)}",
        f"- Unique followed publications: {len(followed)}",
        f"- Author-continuation edges: {rel_counts['author_continuation']}",
        f"- Direct citation edges: {rel_counts['citation']}",
        f"- Strong direct-citation continuations: {lineage_counts['direct_citation_continuation']}",
        f"- Direct citations within same researcher: {lineage_counts['direct_citation_same_author']}",
        f"- Author-only continuations: {lineage_counts['author_continuation_only']}",
        "",
        "## Lineage interpretation",
        "",
        "- Score 1.00: same tracked researcher and the later consecutive paper directly cites the earlier paper.",
        "- Score 0.95: same tracked researcher with a direct citation, but the papers are not consecutive in the publication timeline.",
        "- Score 0.85: direct citation between papers belonging to different tracked researchers.",
        "- Score 0.75: exact ORCID researcher continuation without a direct citation between consecutive papers.",
        "- Score 0.45: name-only researcher continuation without direct citation evidence.",
        "",
        "## Identity policy",
        "",
        "- High confidence: exact ORCID match through PubMed Author Identifier.",
        "- Low confidence: exact full-author-name fallback; manual review is recommended.",
        "- SKKU status here is seeded from publication-time affiliation, not proof of graduation/alumni status.",
        "",
        "## Researchers",
        "",
        "| Researcher | Confidence | ORCID | Followed papers |",
        "|---|---|---|---:|",
    ]
    for tracked in registry:
        lines.append(
            f"| {tracked.name} | {tracked.confidence} | {tracked.orcid or '-'} | "
            f"{len(by_key.get(tracked.key, []))} |"
        )

    lines += ["", "## Publication chains", ""]
    for tracked in registry:
        chain = sorted(
            by_key.get(tracked.key, []),
            key=lambda p: (p.year or 9999, p.pmid),
        )
        if not chain:
            continue
        lines.append(f"### {tracked.name}")
        lines.append(
            f"Confidence: **{tracked.confidence}**"
            + (f" · ORCID: {tracked.orcid}" if tracked.orcid else "")
        )
        for paper in chain:
            aff = "SKKU" if paper.skku_current else "non-SKKU / other affiliation"
            lines.append(
                f"- {paper.year or 'Unknown'} · PMID {paper.pmid} · "
                f"[{paper.title}]({paper.pubmed_url}) · {aff}"
            )
        lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Follow SKKU-seeded authors across later PubMed publications."
    )
    parser.add_argument("--seed-json", default="outputs/skku_pubmed_lineage/papers.json")
    parser.add_argument("--email", default=os.getenv("NCBI_EMAIL", ""))
    parser.add_argument("--api-key", default=os.getenv("NCBI_API_KEY", ""))
    parser.add_argument("--start-year", type=int, default=2002)
    parser.add_argument("--end-year", type=int, default=datetime.now().year)
    parser.add_argument("--max-authors", type=int, default=100)
    parser.add_argument("--max-per-author", type=int, default=200)
    parser.add_argument("--allow-name-fallback", action="store_true")
    parser.add_argument("--with-citations", action="store_true")
    parser.add_argument("--max-citation-checks", type=int, default=300)
    parser.add_argument("--output-dir", default="outputs/skku_pubmed_followup")
    args = parser.parse_args()

    if not args.email:
        parser.error("Provide --email or set NCBI_EMAIL.")

    seed_records = load_seed(Path(args.seed_json))
    registry = build_registry(seed_records, args.allow_name_fallback)
    registry = registry[: args.max_authors]
    print(
        f"[registry] researchers={len(registry)} "
        f"(ORCID-first; name fallback={args.allow_name_fallback})",
        file=sys.stderr,
    )

    client = PubMedClient(args.email, args.api_key)
    papers, paper_authors, registry_map = collect_followups(
        client=client,
        registry=registry,
        start_year=args.start_year,
        end_year=args.end_year,
        max_per_author=args.max_per_author,
    )

    followed = [
        make_followed_paper(papers[pmid], keys, registry_map)
        for pmid, keys in paper_authors.items()
    ]
    followed.sort(key=lambda p: (p.year, p.pmid), reverse=True)

    edges = make_continuation_edges(papers, paper_authors, registry_map)
    if args.with_citations:
        edges = add_direct_citation_edges(
            client,
            papers,
            edges,
            args.max_citation_checks,
        )

    lineage_edges = build_research_lineage_edges(
        edges,
        paper_authors,
        registry_map,
    )

    out = Path(args.output_dir)
    out.mkdir(parents=True, exist_ok=True)

    registry_rows = []
    for item in registry:
        row = asdict(item)
        row["seed_pmids"] = "; ".join(item.seed_pmids)
        registry_rows.append(row)
    write_csv(out / "author_registry.csv", registry_rows)

    followed_rows = []
    for item in followed:
        row = asdict(item)
        row["tracked_authors"] = "; ".join(item.tracked_authors)
        row["tracked_author_keys"] = "; ".join(item.tracked_author_keys)
        row["current_affiliations"] = " | ".join(item.current_affiliations)
        followed_rows.append(row)
    write_csv(out / "lineage_papers.csv", followed_rows)
    write_csv(out / "continuation_edges.csv", [asdict(e) for e in edges])

    lineage_rows = []
    for item in lineage_edges:
        row = asdict(item)
        row["tracked_authors"] = "; ".join(item.tracked_authors)
        lineage_rows.append(row)
    write_csv(out / "lineage_edges.csv", lineage_rows)

    (out / "lineage_papers.json").write_text(
        json.dumps([asdict(x) for x in followed], ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    (out / "continuation_edges.json").write_text(
        json.dumps([asdict(x) for x in edges], ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    (out / "lineage_edges.json").write_text(
        json.dumps([asdict(x) for x in lineage_edges], ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    write_report(out / "continuation.md", registry, followed, edges, lineage_edges)

    summary = {
        "tracked_researchers": len(registry),
        "high_confidence_orcid": sum(x.confidence == "high" for x in registry),
        "low_confidence_name": sum(x.confidence == "low" for x in registry),
        "unique_followed_papers": len(followed),
        "edges": len(edges),
        "edge_types": dict(Counter(e.relation for e in edges)),
        "lineage_edges": len(lineage_edges),
        "lineage_types": dict(Counter(e.relation for e in lineage_edges)),
        "strong_direct_lineage": sum(
            e.relation in {"direct_citation_continuation", "direct_citation_same_author"}
            for e in lineage_edges
        ),
    }
    (out / "summary.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
